//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class favoritos
    {
        public int id { get; set; }
        public string usuarios_id { get; set; }
        public string unha_ide { get; set; }
    }
}
