//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicDB
{
    using System;
    using System.Collections.Generic;
    using Cirrious.MvvmCross.Community.Plugins.Sqlite;
    
    public partial class unha
    {
        [PrimaryKey, AutoIncrement]
        public int id_pk { get; set; }
        public DateTime created_at { get; set; }
        public DateTime updated_at { get; set; }


        public int id { get; set; }
        public string nombre { get; set; }
        public string url { get; set; }
        public string descargas { get; set; }
        public string cant_estrellas { get; set; }

        public int categoria_id { get; set; }
        
        public string fecha_ingreso { get; set; }
        public int pulgar { get; set; }
        

    }
}
