//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicDB
{
    using Cirrious.MvvmCross.ViewModels;
    using System;
    using System.Collections.Generic;
  //  using Cirrious.MvvmCross.Community.Plugins.Sqlite;

    public partial class unha_image : MvxNotifyPropertyChanged
    {
    
        public int id { get; set; }
        public string image_url { get; set; }
        public int card_id { get; set; }

        byte[] _image_bytes;
        public byte[] image_bytes { get { return _image_bytes; } set { _image_bytes = value; RaisePropertyChanged("image_bytes"); } }
    

    }

        

    }

