//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicDB
{
    using System;
    using System.Collections.Generic;
    public partial class usuarios
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string image_url { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string fecha { get; set; }
        public string userid { get; set; }
    }
}
