#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MagicMobile.Resource", IsApplication=true)]

namespace MagicMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ByteSmith.WindowsAzure.Messaging.Resource.String.library_name = global::MagicMobile.Resource.String.library_name;
			global::Gcm.Client.Resource.String.library_name = global::MagicMobile.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int categ1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int categ2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int categ3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int categ4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int categ5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int categ6 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int face = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int lista1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int lista2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int lista3 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int magic1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int magic3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int magic4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int mano_blanca = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int mano_colorada = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int mano_morena = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int mano_roja = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int marco = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int minigatito = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ojo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int PushMensaje = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ra = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int splash = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int tutorial1 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int tutorial2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int tutorial3 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int unha11 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int unha12 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int unha13 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int unia = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int unia_1_01 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int unia_1_02 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int unia_1_03 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int unia_1_04 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int unia_1_05 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int unia_1_06 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int unia_1_07 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int unia_1_08 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int unia_1_09 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int unia_1_10 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int unia_1_11 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int unia_1_12 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int unia_2_01 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int unia_2_02 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int unia_2_03 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int unia_2_04 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int unia_2_05 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int unia_2_06 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int unia_2_07 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int unia_2_08 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int unia_2_09 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int unia_2_10 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int unia_2_11 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int unia_2_12 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int unia_3_01 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int unia_3_02 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int unia_3_03 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int unia_3_04 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int unia_3_05 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int unia_3_06 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int unia_3_07 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int unia_3_08 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int unia_3_09 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int unia_3_10 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int unia_3_11 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int unia_3_12 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int unia_4_01 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int unia_4_02 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int unia_4_03 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int unia_4_04 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int unia_4_05 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int unia_4_06 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int unia_4_07 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int unia_4_08 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int unia_4_09 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int unia_4_10 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int unia_4_11 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int unia_4_12 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int unia_5_01 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int unia_5_02 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int unia_5_03 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int unia_5_04 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int unia_5_05 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int unia_5_06 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int unia_5_07 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int unia_5_08 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int unia_5_09 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int unia_5_10 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int unia_5_11 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int unia_5_12 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int unia_6_01 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int unia_6_02 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int unia_6_03 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int unia_6_04 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int unia_6_05 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int unia_6_06 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int unia_6_07 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int unia_6_08 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int unia_6_09 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int unia_6_10 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int unia_6_11 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int unia_6_12 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int unia_png = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int uniafondo = 2130837608;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int Image1 = 2131034125;
			
			// aapt resource value: 0x7f050060
			public const int List = 2131034208;
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050064
			public const int PushMensaje = 2131034212;
			
			// aapt resource value: 0x7f05000e
			public const int Text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Text1 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int Text2 = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int boton = 2131034118;
			
			// aapt resource value: 0x7f050066
			public const int butregresar = 2131034214;
			
			// aapt resource value: 0x7f050017
			public const int button1 = 2131034135;
			
			// aapt resource value: 0x7f050002
			public const int flash = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int frame = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int gridview = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int imageMayor1 = 2131034133;
			
			// aapt resource value: 0x7f050063
			public const int imageView1 = 2131034211;
			
			// aapt resource value: 0x7f050067
			public const int imgaumentada = 2131034215;
			
			// aapt resource value: 0x7f050061
			public const int layout1 = 2131034209;
			
			// aapt resource value: 0x7f050065
			public const int layoutx = 2131034213;
			
			// aapt resource value: 0x7f050007
			public const int myButtonCateg1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int myButtonCateg2 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int myButtonCateg3 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int myButtonCateg4 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int myButtonCateg5 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int myButtonCateg6 = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int myButtonDisenho1 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int myButtonDisenho2 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int myButtonDisenho3 = 2131034131;
			
			// aapt resource value: 0x7f050062
			public const int myButtonFacebook = 2131034210;
			
			// aapt resource value: 0x7f050004
			public const int overlay = 2131034116;
			
			// aapt resource value: 0x7f050069
			public const int ra_nogusto = 2131034217;
			
			// aapt resource value: 0x7f050068
			public const int ra_ok = 2131034216;
			
			// aapt resource value: 0x7f050016
			public const int ratingbar = 2131034134;
			
			// aapt resource value: 0x7f050003
			public const int surface = 2131034115;
			
			// aapt resource value: 0x7f05006a
			public const int textCat = 2131034218;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050018
			public const int unia_1_01 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int unia_1_02 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int unia_1_03 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int unia_1_04 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int unia_1_05 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int unia_1_06 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int unia_1_07 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int unia_1_08 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int unia_1_09 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int unia_1_10 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int unia_1_11 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int unia_1_12 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int unia_2_01 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int unia_2_02 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int unia_2_03 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int unia_2_04 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int unia_2_05 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int unia_2_06 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int unia_2_07 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int unia_2_08 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int unia_2_09 = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int unia_2_10 = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int unia_2_11 = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int unia_2_12 = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int unia_3_01 = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int unia_3_02 = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int unia_3_03 = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int unia_3_04 = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int unia_3_05 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int unia_3_06 = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int unia_3_07 = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int unia_3_08 = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int unia_3_09 = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int unia_3_10 = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int unia_3_11 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int unia_3_12 = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int unia_4_01 = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int unia_4_02 = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int unia_4_03 = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int unia_4_04 = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int unia_4_05 = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int unia_4_06 = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int unia_4_07 = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int unia_4_08 = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int unia_4_09 = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int unia_4_10 = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int unia_4_11 = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int unia_4_12 = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int unia_5_01 = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int unia_5_02 = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int unia_5_03 = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int unia_5_04 = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int unia_5_05 = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int unia_5_06 = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int unia_5_07 = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int unia_5_08 = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int unia_5_09 = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int unia_5_10 = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int unia_5_11 = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int unia_5_12 = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int unia_6_01 = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int unia_6_02 = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int unia_6_03 = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int unia_6_04 = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int unia_6_05 = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int unia_6_06 = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int unia_6_07 = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int unia_6_08 = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int unia_6_09 = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int unia_6_10 = 2131034205;
			
			// aapt resource value: 0x7f05005e
			public const int unia_6_11 = 2131034206;
			
			// aapt resource value: 0x7f05005f
			public const int unia_6_12 = 2131034207;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int awesome = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CapturaMano = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Catalogo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CatalogoFinal = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DisenhosPorCatalogo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DisenhosPorCatalogoGrid = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DisenhoView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FirstView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Grid1 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Grid2 = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Grid3 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Grid4 = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Grid5 = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Grid6 = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int GridX = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int HomeScreen = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Item_Unias = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int MainView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Mensaje = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ModoAvatar = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int RealidadAumentada = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int SplashScreen = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int UniasView = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int callHistory = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int openCamera = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
